server:
  port: 8089

spring:
  application:
    title: roadpricing-gateway
    name: roadpricing-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
logging:
  level:
    org:
      springframework:
        security: DEBUG
        cloud:
          gateway: DEBUG
